// 表示名・ブランド色・ロゴ(simple-icons slug)のマスタ。ランキング入りし得る銘柄を広めに持つ。
// key: 日本=証券コード / 米国=ティッカー
module.exports = {
  jp: {
    "7203": { en: "Toyota", name: "トヨタ自動車", color: "#EB0A1E", si: "toyota" },
    "8306": { en: "Mitsubishi UFJ", name: "三菱UFJフィナンシャル・グループ", color: "#E60012", si: "mitsubishi" },
    "9984": { en: "SoftBank Group", name: "ソフトバンクグループ", color: "#1A1A1A", mono: "SBG" },
    "285A": { en: "Kioxia", name: "キオクシアホールディングス", color: "#0F2D6B", mono: "KX" },
    "8035": { en: "Tokyo Electron", name: "東京エレクトロン", color: "#E60012", mono: "TEL" },
    "8316": { en: "Sumitomo Mitsui Financial", name: "三井住友フィナンシャルグループ", color: "#004831", mono: "SM" },
    "6857": { en: "Advantest", name: "アドバンテスト", color: "#8A1538", mono: "ADV" },
    "6501": { en: "Hitachi", name: "日立製作所", color: "#E60027", si: "hitachi" },
    "6098": { en: "Recruit", name: "リクルートホールディングス", color: "#0055A4", mono: "R" },
    "6758": { en: "Sony", name: "ソニーグループ", color: "#000000", si: "sony" },
    "9983": { en: "Fast Retailing", name: "ファーストリテイリング", color: "#FF0000", si: "uniqlo" },
    "8411": { en: "Mizuho", name: "みずほフィナンシャルグループ", color: "#0033A0", mono: "M" },
    "8058": { en: "Mitsubishi Corp", name: "三菱商事", color: "#E60012", si: "mitsubishi" },
    "7011": { en: "Mitsubishi Heavy", name: "三菱重工業", color: "#E60012", si: "mitsubishi" },
    "8766": { en: "Tokio Marine", name: "東京海上ホールディングス", color: "#00843D", mono: "TM" },
    "6861": { en: "Keyence", name: "キーエンス", color: "#1C4E9D", mono: "K" },
    "9432": { en: "Nippon Telegraph", name: "NTT", color: "#0072BC", mono: "NTT" },
    "8031": { en: "Mitsui & Co", name: "三井物産", color: "#003C8C", mono: "三井" },
    "8001": { en: "Itochu", name: "伊藤忠商事", color: "#0068B7", mono: "C" },
    "4519": { en: "Chugai", name: "中外製薬", color: "#C8102E", mono: "中外" },
    "4063": { en: "Shin-Etsu", name: "信越化学工業", color: "#004EA2", mono: "信越" },
    "7974": { en: "Nintendo", name: "任天堂", color: "#E60012", si: "nintendo", mono: "N" },
    "2914": { en: "Japan Tobacco", name: "日本たばこ産業", color: "#00A0E9", mono: "JT" },
    "9433": { en: "KDDI", name: "KDDI", color: "#1C1C1C", mono: "au" },
    "6503": { en: "Mitsubishi Electric", name: "三菱電機", color: "#E60012", si: "mitsubishi" },
    "9434": { en: "SoftBank Corp", name: "ソフトバンク", color: "#1A1A1A", mono: "SB" },
    "7267": { en: "Honda", name: "本田技研工業", color: "#E40521", si: "honda" },
    "8002": { en: "Marubeni", name: "丸紅", color: "#E60012", mono: "丸紅" },
    "7182": { en: "Japan Post Bank", name: "ゆうちょ銀行", color: "#00A650", mono: "〒" },
    "7741": { en: "Hoya", name: "HOYA", color: "#003B87", mono: "H" },
    "5803": { en: "Fujikura", name: "フジクラ", color: "#004098", mono: "F" },
    "8053": { en: "Sumitomo Corp", name: "住友商事", color: "#1A3B8C", mono: "住商" },
    "4502": { en: "Takeda", name: "武田薬品工業", color: "#E4002B", mono: "T" },
    "6702": { en: "Fujitsu", name: "富士通", color: "#E60012", mono: "F" },
    "6981": { en: "Murata", name: "村田製作所", color: "#0063B1", mono: "M" },
    "8591": { en: "ORIX", name: "オリックス", color: "#F08300", mono: "O" },
    "6902": { en: "Denso", name: "デンソー", color: "#DC0032", mono: "D" },
    "4568": { en: "Daiichi Sankyo", name: "第一三共", color: "#C8102E", mono: "DS" },
    "6178": { en: "Japan Post Holdings", name: "日本郵政", color: "#E60012", mono: "〒" },
    "6367": { en: "Daikin", name: "ダイキン工業", color: "#0097E0", mono: "D" },
    "6752": { en: "Panasonic", name: "パナソニック ホールディングス", color: "#0041C0", mono: "P" },
    "6146": { en: "Disco", name: "ディスコ", color: "#E60012", mono: "D" },
    "7751": { en: "Canon", name: "キヤノン", color: "#CC0000", mono: "C" },
  },
  us: {
    NVDA: { name: "エヌビディア", color: "#76B900", si: "nvidia" },
    AAPL: { name: "アップル", color: "#000000", si: "apple" },
    GOOG: { name: "アルファベット", color: "#4285F4", si: "google" },
    MSFT: { name: "マイクロソフト", color: "#00A4EF", mono: "MS" },
    AMZN: { name: "アマゾン・ドット・コム", color: "#FF9900", mono: "a" },
    AVGO: { name: "ブロードコム", color: "#E31837", si: "broadcom" },
    META: { name: "メタ・プラットフォームズ", color: "#0467DF", si: "meta" },
    TSLA: { name: "テスラ", color: "#CC0000", si: "tesla" },
    "BRK-B": { name: "バークシャー・ハサウェイ", color: "#1B2A4A", mono: "BRK" },
    JPM: { name: "JPモルガン・チェース", color: "#1A1A1A", mono: "JPM" },
    LLY: { name: "イーライリリー", color: "#D52B1E", mono: "Lilly" },
    WMT: { name: "ウォルマート", color: "#0071CE", mono: "W" },
    V: { name: "ビザ", color: "#1A1F71", si: "visa" },
    ORCL: { name: "オラクル", color: "#C74634", mono: "O" },
    MA: { name: "マスターカード", color: "#EB001B", si: "mastercard" },
    XOM: { name: "エクソンモービル", color: "#ED1B2F", mono: "XOM" },
    NFLX: { name: "ネットフリックス", color: "#E50914", si: "netflix" },
    COST: { name: "コストコ", color: "#E31837", mono: "C" },
    JNJ: { name: "ジョンソン・エンド・ジョンソン", color: "#D51900", mono: "J&J" },
    PLTR: { name: "パランティア", color: "#101113", si: "palantir" },
    AMD: { name: "AMD", color: "#ED1C24", si: "amd" },
    BAC: { name: "バンク・オブ・アメリカ", color: "#012169", si: "bankofamerica" },
    HD: { name: "ホーム・デポ", color: "#F96302", mono: "HD" },
    PG: { name: "P&G", color: "#003DA5", mono: "P&G" },
    ABBV: { name: "アッヴィ", color: "#071D49", si: "abbvie" },
    UNH: { name: "ユナイテッドヘルス", color: "#002677", mono: "U" },
    MU: { name: "マイクロン・テクノロジー", color: "#0E3B7A", mono: "M" },
    CSCO: { name: "シスコシステムズ", color: "#1BA0D7", si: "cisco" },
    KO: { name: "コカ・コーラ", color: "#F40009", mono: "KO" },
    CVX: { name: "シェブロン", color: "#0054A4", mono: "CVX" },
    GE: { name: "GEエアロスペース", color: "#005EB8", mono: "GE" },
    IBM: { name: "IBM", color: "#054ADA", mono: "IBM" },
    WFC: { name: "ウェルズ・ファーゴ", color: "#D71E28", mono: "WF" },
    CRM: { name: "セールスフォース", color: "#00A1E0", mono: "CRM" },
    LRCX: { name: "ラムリサーチ", color: "#0033A0", mono: "LR" },
    AMAT: { name: "アプライド・マテリアルズ", color: "#1A5DAB", mono: "AM" },
    MS: { name: "モルガン・スタンレー", color: "#002F6C", mono: "MS" },
    GS: { name: "ゴールドマン・サックス", color: "#6F9FD8", mono: "GS" },
    INTC: { name: "インテル", color: "#0071C5", mono: "i" },
  },
};
